// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBQkyT-ypiWZTNSTSs6qox9DCSlSODLLCA',
    appId: '1:538970421559:web:157f031dd919ee8ec582b2',
    messagingSenderId: '538970421559',
    projectId: 'ev-charging-point-app',
    authDomain: 'ev-charging-point-app.firebaseapp.com',
    storageBucket: 'ev-charging-point-app.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBrdU3JsgF6qX7v0gaudkz2WUc0Gm53b5I',
    appId: '1:538970421559:android:bfbac02dee7f0b27c582b2',
    messagingSenderId: '538970421559',
    projectId: 'ev-charging-point-app',
    storageBucket: 'ev-charging-point-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBX8CnoCe7GM15eiZzhr1OgDBeZ1A-b8JM',
    appId: '1:538970421559:ios:05775001c5786eb1c582b2',
    messagingSenderId: '538970421559',
    projectId: 'ev-charging-point-app',
    storageBucket: 'ev-charging-point-app.appspot.com',
    iosBundleId: 'com.example.evChargingPointApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBX8CnoCe7GM15eiZzhr1OgDBeZ1A-b8JM',
    appId: '1:538970421559:ios:995a8658326694c5c582b2',
    messagingSenderId: '538970421559',
    projectId: 'ev-charging-point-app',
    storageBucket: 'ev-charging-point-app.appspot.com',
    iosBundleId: 'com.example.evChargingPointApp.RunnerTests',
  );
}
